export * from './address-info-form/address-info-form.component';
export * from './contact-info-form/contact-info-form.component';
export * from './education-medical-worker-info-form/education-medical-worker-info-form.component';
export * from './identification-info-form/identification-info-form.component';
export * from './identification-info-form/identification-info-form-for-citizens-belarus/identification-info-form-for-citizens-belarus.component';
export * from './identification-info-form/identification-info-form-for-foreign-citizens/identification-info-form-for-foreign-citizens.component';
export * from './mobile-phone-number-password-info-form/mobile-phone-number-password-info-form.component';
export * from './personal-info-form/personal-info-form.component';
export * from './place-work-info-form/place-work-info-form.component';
